{% set name = "pyrosar" %}
{% set version = "0.33.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e4ded8a38d63c15b7b8cb22c925b3996198225b2b94c8e43adee8116d86c88c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - gdal >=2.4
    - geoalchemy2 <0.14.0
    - libgdal
    - libspatialite >=5.1.0
    - lxml
    - numpy
    - packaging
    - pillow
    - progressbar2
    - psycopg2
    - python >={{ python_min }}
    - pyyaml
    - requests
    - spatialist >=0.16.2
    - sqlalchemy >=1.4,<2.0
    - sqlalchemy-utils >=0.37,<0.42

test:
  imports:
    - pyroSAR
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/johntruckenbrodt/pyroSAR
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python Framework for Large-Scale SAR Satellite Data Processing

  description: |
    The pyroSAR package aims at providing a complete solution for the scalable organization and processing of SAR satellite data.
  doc_url: https://pyrosar.readthedocs.io
  dev_url: https://github.com/johntruckenbrodt/pyroSAR

extra:
  recipe-maintainers:
    - johntruckenbrodt
