{% set name = "pyroSAR" %}
{% set version = "0.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: acb1c213f0b1a1cb339b0a96c29119145e8eac37df0d126219eb7b42b5ed5b00

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.0
    - pip
    - setuptools_scm
  run:
    - python >=3.0
    - gdal >=2.4
    - spatialist >=0.10.1
    - progressbar2
    - numpy
    - pyyaml
    - requests
    - psycopg2
    - sqlalchemy >=1.4
    - sqlalchemy-utils >=0.37
    - geoalchemy2

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - pyroSAR
  commands:
    - pytest --ignore=tests/test_snap.py --ignore=tests/test_drivers.py

about:
  home: https://github.com/johntruckenbrodt/pyroSAR
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python Framework for Large-Scale SAR Satellite Data Processing

  description: |
    The pyroSAR package aims at providing a complete solution for the scalable organization and processing of SAR satellite data.
  doc_url: https://pyroSAR.readthedocs.io
  dev_url: https://github.com/johntruckenbrodt/pyroSAR

extra:
  recipe-maintainers:
    - johntruckenbrodt
