{% set name = "pyrosar" %}
  {% set version = "0.28.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d937fd99d98d335bd830c1af33476453be1daa792c07de3555c1287ed17cd37b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - gdal >=2.4
    - spatialist >=0.12.1
    - progressbar2
    - numpy <2.0
    - pyyaml
    - requests
    - psycopg2
    - sqlalchemy >=1.4,<2.0
    - sqlalchemy-utils >=0.37
    - geoalchemy2 <0.14.0
    - pillow
    - lxml
    - packaging
    - libspatialite >=5.1.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyroSAR

about:
  home: https://github.com/johntruckenbrodt/pyroSAR
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python Framework for Large-Scale SAR Satellite Data Processing

  description: |
    The pyroSAR package aims at providing a complete solution for the scalable organization and processing of SAR satellite data.
  doc_url: https://pyrosar.readthedocs.io
  dev_url: https://github.com/johntruckenbrodt/pyroSAR

extra:
  recipe-maintainers:
    - johntruckenbrodt
