{% set name = "pyrosar" %}
{% set version = "0.30.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23a25987d594f56acbe2478f0e7a286815fe861dba571a1732303cf5651020eb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - gdal >=2.4
    - geoalchemy2 <0.14.0
    - libgdal
    - libspatialite >=5.1.0
    - lxml
    - numpy <2.0
    - packaging
    - pillow
    - progressbar2
    - psycopg2
    - python >={{ python_min }}
    - pyyaml
    - requests
    - spatialist >=0.15.2
    - sqlalchemy >=1.4,<2.0
    - sqlalchemy-utils >=0.37

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyroSAR

about:
  home: https://github.com/johntruckenbrodt/pyroSAR
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python Framework for Large-Scale SAR Satellite Data Processing

  description: |
    The pyroSAR package aims at providing a complete solution for the scalable organization and processing of SAR satellite data.
  doc_url: https://pyrosar.readthedocs.io
  dev_url: https://github.com/johntruckenbrodt/pyroSAR

extra:
  recipe-maintainers:
    - johntruckenbrodt
