{% set name = "pyroSAR" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b7fa8dcb9909f22cb9e333b06bea029989bee6d4043415973c8bd7e7bb2765c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.0
    - pip
    - setuptools_scm
  run:
    - python >=3.0
    - gdal >=2.4
    - spatialist >=0.11.0
    - progressbar2
    - numpy
    - pyyaml
    - requests
    - psycopg2
    - sqlalchemy >=1.4
    - sqlalchemy-utils >=0.37
    - geoalchemy2
    - pillow
    - lxml

test:
  imports:
    - pyroSAR

about:
  home: https://github.com/johntruckenbrodt/pyroSAR
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python Framework for Large-Scale SAR Satellite Data Processing

  description: |
    The pyroSAR package aims at providing a complete solution for the scalable organization and processing of SAR satellite data.
  doc_url: https://pyroSAR.readthedocs.io
  dev_url: https://github.com/johntruckenbrodt/pyroSAR

extra:
  recipe-maintainers:
    - johntruckenbrodt
