{% set name = "pyroSAR" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 78276d8b345174deeac70ffdefc54928152da7a06771ee1a91182db2ed8022cb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.0
    - pip
    - setuptools_scm
  run:
    - python >=3.0
    - gdal >=2.4
    - spatialist >=0.8
    - progressbar2
    - numpy
    - pyyaml
    - requests
    - psycopg2
    - sqlalchemy >=1.4
    - sqlalchemy-utils >=0.37
    - geoalchemy2

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - pyroSAR
  commands:
    - pytest --ignore=tests/test_snap.py --ignore=tests/test_drivers.py

about:
  home: https://github.com/johntruckenbrodt/pyroSAR
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python Framework for Large-Scale SAR Satellite Data Processing

  description: |
    The pyroSAR package aims at providing a complete solution for the scalable organization and processing of SAR satellite data.
  doc_url: https://pyroSAR.readthedocs.io
  dev_url: https://github.com/johntruckenbrodt/pyroSAR

extra:
  recipe-maintainers:
    - johntruckenbrodt
