{% set name = "pyroSAR" %}
{% set version = "0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a53c4fa8ab9b0e8a59a01031c25f12bdab3a8e04dc7f0e8660832cfde395c1c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.0
    - pip
    - setuptools_scm
  run:
    - python >=3.0
    - gdal >=2.2
    - spatialist >=0.8
    - progressbar2
    - pathos >=0.2
    - numpy
    - pyyaml
    - requests
    - psycopg2
    - sqlalchemy <1.4
    - sqlalchemy-utils
    - geoalchemy2

test:
  source_files:
    - pyroSAR/tests
  requires:
    - pytest
  imports:
    - pyroSAR
  commands:
    - pytest --ignore=pyroSAR/tests/test_snap.py --ignore=pyroSAR/tests/test_drivers.py

about:
  home: https://github.com/johntruckenbrodt/pyroSAR
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python Framework for Large-Scale SAR Satellite Data Processing

  description: |
    The pyroSAR package aims at providing a complete solution for the scalable organization and processing of SAR satellite data.
  doc_url: https://pyroSAR.readthedocs.io
  dev_url: https://github.com/johntruckenbrodt/pyroSAR

extra:
  recipe-maintainers:
    - johntruckenbrodt
